config/routes.rb
Rails.application.routes.draw do
  mount Lines::Engine => "/blog"
  get '/blog/article/:id' => "lines/articles#show", as: 'article'
  get '/about' => 'home#about'
  get '/services' => 'home#services'
  get '/contact' => 'home#contact'
  get '/careers' => 'home#careers'
  post '/enquiry' => 'home#enquiry'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        item('Article Categories', path: admin_article_categories_path),
        item('Articles', path: admin_articles_path),
        # scaffold inject marker
      ]
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @nav_class = "absolute transparent"
  end

  def about
    @nav_class = "absolute transparent"
  end

  def services
    @nav_class = "absolute transparent"
  end

  def contact
  end

  def blog
  end

  def appointment
  end

  def careers
  end

  def enquiry
    service = EnquiryNotificationService.new(params)
    
    if service.valid?
      service.notify
      flash[:success] = "Thank you! We’ll get back to you as soon as possible at #{params[:email]}"
      redirect_to root_path
    else
      flash[:warning] = "There was an error sending your message. Please try again."
      redirect_to contact_path
    end
  end
end

app/controllers/lines/articles_controller.rb
# Lists all Articles and shows specific ones.
# Responds either to HTML and ATOM requests.
require 'acts-as-taggable-on'
require_dependency "lines/application_controller"

module Lines

  class ArticlesController < ApplicationController

    layout 'lines/blogs'

    KEYWORDS = CONFIG[:keywords]
    SITE_TITLE = CONFIG[:title]

    # Lists all published articles.
    # Responds to html and atom
    def index
      @tags = ActsAsTaggableOn::Tag.distinct.pluck(:name)
      @tag = params[:tag] || 'all'
      @current_page = params[:page].to_i
      if params[:tag]
        @articles = Lines::Article.published.tagged_with(params[:tag]).page(params[:page].to_i)
      else
        @articles = Lines::Article.published.page(params[:page].to_i)
      end
      respond_to do |format|
        format.html do
          set_meta_tags title: SITE_TITLE,
                        description: CONFIG[:meta_description],
                        keywords: KEYWORDS,
                        open_graph: { title: SITE_TITLE,
                                        type: 'website',
                                        url: articles_url,
                                        site_name: SITE_TITLE,
                                        image: CONFIG[:og_logo]
                                      }
        end
        format.js
        format.atom do
          @articles = Lines::Article.published
        end
      end
    end

    def show
      @article = Lines::Article.published.find(params[:id])
      meta_tags = { title: @article.title,
        type: 'article',
        url: url_for(@article),
        site_name: SITE_TITLE,
      }
      meta_tags[:image] = CONFIG[:host] + @article.image_url if @article.image_url.present?
      set_meta_tags title: @article.title,
                    keywords: KEYWORDS + @article.tag_list.to_s,
                    open_graph: meta_tags

      @related_articles = Lines::Article.published.where('id != ?', @article.id).order('').limit(2)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<section class="general-banner">
  <div class="container">
    <div class="row no-gutters position-relative">
      <div class="col-lg-4 col-sm-12 d-flex align-items-center">
        <div class="general-banner-left">
          <h3 class="general-banner-title general-big-title text-uppercase">KVY TECH</h3>
          <p class="general-banner-text general-title">
            Our vision is to use our passion for technology, content and services to deliver excellence products and services.
          </p>
        </div>
      </div>
      <div
        class="col-lg-8 col-sm-12 mt-lg-0 mt-2 d-flex align-items-center"
        >
        <img
          class="img-fluid"
          src="<%= image_url('story-banner.png') %>"
          alt="kvy-technology"

          />
      </div>
    </div>
  </div>
</section>
<!-- <section class="story-support position-relative">
  <div class="container">
    <div class="row no-gutters">
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center pt-4"
        >
        <div class="story-support-item">
          <strong class="home-content-title d-block">Our Teams</strong>
          <p class="home-text">
            We’re small team of specialists in backend, frontend, and devops engineers.
          </p>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('man.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Man Vuong</p>
          <p class="story-support-position">Technical Director</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('vu.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Vu Tran</p>
          <p class="story-support-position">Elixir/Rails Developer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('trungtt.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Trung Tran</p>
          <p class="story-support-position">Frontend Developer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('quan.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Quan Phuong</p>
          <p class="story-support-position">Solution Architect</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('nghia.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Nghia Doan</p>
          <p class="story-support-position">Frontend Developer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('dong.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Dong Tran</p>
          <p class="story-support-position">UI/UX Designer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('dung.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Dung Vu</p>
          <p class="story-support-position">Software Engineer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('bich.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Hoang Bich</p>
          <p class="story-support-position">Accounting Manager</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('tung.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Tung Pham</p>
          <p class="story-support-position">Backend Engineer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('minh.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name">Minh Dang</p>
          <p class="story-support-position">Fullstack Engineer</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('long.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Long Nguyen</p>
          <p class="story-support-position">Managing Director</p>
        </div>
        </div>
      </div>
      <div
        class="col-lg-3 col-md-4 col-sm-6 col-12 text-sm-left text-center "
        >
        <div class="story-support-item">
          <div class="story-support-avatar position-relative">
            <img
              class="img-fluid lozad"
              data-src="<%= image_url('hung.jpg') %>"
              alt="kvy-technology"

              />
          </div>
        <div class="mt-2">
          <p class="story-support-name general-title">Hung Nguyen</p>
          <p class="story-support-position">Business Manager</p>
        </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-8 col-12">
        <div class="story-support-item next">
          <div>
            <h5 class="story-support-item-title general-big-title  d-inline-block">The Next Members</h5>
            <p class="home-text">We want to create a place that our team members enjoy to work and our clients enjoy to work with us.</p>
            <a href="./careers"  class="home-button text-uppercase d-inline-block">Join our Team</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->
<section class="story-value">
  <div class="container">
    <strong class="story-value-title general-big-title-height d-block text-center">Our Values</strong>
    <div class="row no-gutters">
      <div class="col-lg-3 col-md-6 col-sm-6 mt-lg-0 mt-4">
        <div class="story-value-item text-center">
          <img
            class="img-fluid story-icon"
            src="<%= image_url('story-excellence.svg') %>"
            alt="kvy-technology"

            />
            <img
              class="img-fluid story-icon-hover"
              src="<%= image_url('story-excellence-hover.svg') %>"
              alt="kvy-technology"

              />
              <strong class="story-value-subtitle d-block mt-4 pt-2">Excellence</strong>
              <p class="home-text">
                We strive to deliver the highest quality and value possible through simple, easy and relevant solutions
              </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6 col-12 mt-lg-0 mt-4">
        <div
          class="story-value-item text-center"
          >
          <img
            class="img-fluid story-icon"
            src="<%= image_url('story-integrity.svg') %>"
            alt="kvy-technology"

            />
          <img
            class="img-fluid story-icon-hover"
            src="<%= image_url('story-integrity-hover.svg') %>"
            alt="kvy-technology"

            />
            <strong class="story-value-subtitle d-block mt-4 pt-2">Integrity & Sincerity</strong>
            <p class="home-text">
              Integrity is the foundation of how we operate our business. It is the moral compass to ensure fairness, transparency in order to building sustainable relationships.
            </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6 col-12 mt-lg-0 mt-4">
        <div
          class="story-value-item text-center"
          >
          <img
            class="img-fluid story-icon"
            src="<%= image_url('story-fun.svg') %>"
            alt="kvy-technology"

            />
          <img
            class="img-fluid story-icon-hover"
            src="<%= image_url('story-fun-hover.svg') %>"
            alt="kvy-technology"

            />
            <strong class="story-value-subtitle d-block mt-4 pt-2">Fun</strong>
            <p class="home-text">
              We want to create a place that our team members enjoy to work and our clients enjoy to work with us.
            </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6 col-12 mt-lg-0 mt-4">
        <div
          class="story-value-item text-center"
          >
          <img
            class="img-fluid story-icon"
            src="<%= image_url('story-sustainability.svg') %>"
            alt="kvy-technology"

            />
          <img
            class="img-fluid story-icon-hover"
            src="<%= image_url('story-sustainability-hover.svg') %>"
            alt="kvy-technology"

            />
            <strong class="story-value-subtitle d-block mt-4 pt-2">Sustainability</strong>
            <p class="home-text">
              We will build our business sustainably through passionate and loyal customers.
            </p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="story-join d-flex align-items-center">
  <div class="container">
    <div class="row no-gutters">
      <div class="story-join-wrapper w-100 text-center">
        <strong class="home-content-title">Let's Work Together</strong>
        <p class="home-text">
          Through our custom software development consulting, we'll help you understand where and how your team can improve as we help you bring your technology to market faster. Your team will be stronger after working with KVY Tech.
        </p>
        <a href="careers" >
          <button class="home-button">GET STARTED</button>
        </a>
      </div>
    </div>
  </div>
</section>

app/views/home/blog.html.erb
<div class="main-container">
  <section class="page-title page-title-4 bg-secondary image-bg overlay parallax">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h3 class="uppercase mb0">Blog</h3>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="feed-item mb96 mb-xs-48">
        <div class="row mb16 mb-xs-0">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
            <h6 class="uppercase mb16 mb-xs-8">September 8th</h6>
            <h3>A clean, simple way to share
              <br /> basic updates about your company.</h3>
          </div>
        </div>
        <div class="row mb32 mb-xs-16">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
            <p class="lead">
              Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
            </p>
            <p class="lead">
              Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
            <a class="mb48 mb-xs-32 btn btn-lg" href="#">Share Article</a>
            <hr>
          </div>
        </div>
      </div>
      <div class="feed-item mb96">
        <div class="row mb16 mb-xs-0">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
            <h6 class="uppercase mb16 mb-xs-8">September 4th</h6>
            <h3>You can still embed media types
              <br /> using this blog type.</h3>
          </div>
        </div>
        <div class="row mb32 mb-xs-16">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
            <p class="lead">
              Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
            </p>
            <p class="lead">
              Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur
            </p>
          </div>
        </div>
        <!--end of row-->
        <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
            <a class="mb48 mb-xs-32 btn btn-lg" href="#">Share Article</a>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/home/contact.html.erb
<div class="contact">
  <section class="touch <%= 'mt-0' if flash[:warning] %>">
    <div class="touch-content">
      <div class="container-fluid px-0">
        <div class="row no-gutters">
          <div class="col-lg-6 col-12 pr-lg-4 touch-left">
            <%= image_tag('touch-banner.png', class: 'd-lg-none d-block img-fluid', alt: 'kvy-tech') %>
            <div class="touch-mansory">
              <div class="container-mansory">
                <div class="item pt-0">
                  <%= image_tag('touch-left-01.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-02.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-03.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-04.png', alt: 'kvy-tech') %>
                </div>
                <div class="item pt-0">
                  <%= image_tag('touch-left-05.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-06.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-07.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-08.png', alt: 'kvy-tech') %>
                </div>
                <div class="item pt-0">
                  <%= image_tag('touch-left-09.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-10.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-13.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-11.png', alt: 'kvy-tech') %>
                </div>
                <div class="item">
                  <%= image_tag('touch-left-12.png', alt: 'kvy-tech') %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-12 px-4 position-relative">
            <div class="touch-right">
              <h4 class="touch-title pt-4">
                Hire us to help you build excellent software
              </h4>
              <div class="container-fluid p-0">
                <div class="row">
                  <div class="col-lg-6 col-12 touch-item">
                    <div class="d-flex align-items-start mt-3 mr-2">
                      <div class="touch-icon-warpper d-flex align-items-center">
                        <%= image_tag('contact-email.svg', alt: 'kvy-tech') %>
                      </div>
                      <p class="home-text touch-info">
                        hello@kvytechnology.com
                      </p>
                    </div>
                  </div>
                  <div class="col-lg-6 col-12 touch-item">
                    <div class="d-flex align-items-start mt-3 mr-2">
                      <div class="touch-icon-warpper d-flex align-items-center">
                        <%= image_tag('contact-phone.svg', alt: 'kvy-tech') %>
                      </div>
                      <p class="home-text touch-info">(084) 93636 2488</p>
                    </div>
                  </div>
                  <div class="col-lg-6 col-12 touch-item">
                    <div class="d-flex align-items-start mt-3 mr-2">
                      <div class="touch-icon-warpper d-flex align-items-center">
                        <%= image_tag('contact-map.svg', alt: 'kvy-tech') %>
                      </div>
                      <p class="home-text touch-info">
                        9 Hoa Cau, Phu Nhuan District, HCMC, Viet Nam
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <%= form_tag enquiry_path do %>
                <div class="form-group mb-3">
                  <%= label_tag :name, "Full name", class:"touch-label mb-1" %>
                  <%= text_field_tag :name, nil, class:"form-control", id:"fullname" %>
                </div>
                <div class="form-group mb-3">
                  <%= label_tag :email, "Email", class:"touch-label mb-1" %>
                  <%= text_field_tag :email, nil, class:"form-control", id:"formGroupExampleInput2" %>
                </div>
                <div class="form-group mb-3">
                  <%= label_tag :message,"Message", class:"touch-label mb-1" %>
                  <%= text_area_tag :message, nil, class:"form-control", id:"message", rows: 5 %>
                </div>
                <div class="form-group mb-3">
                  <%= submit_tag 'SEND', class:"touch-submit" %>
                </div>
              <% end %>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/home/partials/_main.html.erb
<div class="main-container">
  <%= render 'home/partials/sections/section1' %>
  <%= render 'home/partials/sections/section2' %>
  <%= render 'home/partials/sections/section3' %>

  <%= render 'home/partials/sections/section7' %>

  <%= render 'home/partials/footer' %>
</div>

app/views/home/partials/sections/_section4.html.erb
<section class="pt240 pb240 image-bg parallax">
                <div class="background-image-holder fadeIn" style="transform: translate3d(0px, 158.5px, 0px); background: url(&quot;img/capital4.jpg&quot;);">
                    <%= image_tag('capital4.jpg', class: 'background-image') %>

                </div>
            </section>

app/views/home/partials/sections/_section7.html.erb
<section class="fullscreen image-bg parallax background-multiply">
    <div class="background-image-holder">
        <%= image_tag('capital2.jpg', class: 'background-image') %>
    </div>
    <div class="container v-align-transform">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1 class="large mb0">See you soon.</h1>
            </div>
        </div>
        <!--end of row-->
    </div>
    <!--end of container-->
</section>

app/views/lines/articles/_article.html.erb
<div class="article first">
  <% cache article do %>
    <% unless article.image_url.blank? %>
      <div class="hero_image">
        <%= link_to article_path(article) do %>
          <img src="<%= article.image_url %>" alt="<%= article.title %>" />
        <% end %>
      </div>
    <% end %>

    <div class="article_header">
      <h1><%= link_to article.title, article_path(article) %></h1>
      <h2><%= article.sub_title %></h2>
      <div class="author_name"><span>by</span> <%= display_article_authors(article) %></div>
    </div>

    <div class="article_teaser">
      <%= render_teaser(article, article_counter) %>
    </div>

    <div class="article_content">
      <%= markdown article.content %>
      <% if article.document? %>
        <div class="article_document">
          <%= link_to "Download #{article.document.file.filename}", article.document_url %>
        </div>
      <% end %>
    </div>

    <% unless article.gplus_url.blank? %>
      <div class="article_googleplus">
        <a href="<%= article.gplus_url %>">Discuss this article at Google+</a>
      </div>
    <% end %>

    <hr>

    <div class="article_footer">
      Written on <span class="published_at"><%= article.published_at.to_date %></span> by <%= display_article_authors(article, true) %>
    </div>
  <% end %>
</div>

app/views/lines/articles/_article_preview.html.erb
<% cache article do %>
  <%= link_to article_path(article) do %>
    <div class="row no-gutters blog-tab-item">
      <div class="col-lg-4 col-md-5 col-12">
        <img
          class="blog-tab-image"
          src="<%= article.image_url %>"
          alt=""
          srcset=""
          />
      </div>
      <div class="col-lg-8 col-md-7 col-12 position-relative blog-tab-content-wrapper">
        <div class="blog-tab-content">
          <h3 class="blog-tab-title mt-0"><%= article.title %></h3>
          <p class="home-text">
            <%= article.teaser %>
          </p>
          <div class="blog-tab-footer position-absolute">
            <span class="text-uppercase">By: <%= article.authors.map(&:name).join(', ') %></span>
            <span class="text-uppercase news"><%= article.tags.map(&:name).join(', ') %></span>
            <span class="text-uppercase"><%= article.published_at.strftime('%d/%m/%Y - %H:%M') %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/lines/articles/_article_small.html.erb
<%= link_to article_path(article) do %>
  <div class="row no-gutters blog-tab-item">
    <div class="col-lg-4 col-md-5 col-12 ">
      <%= image_tag article.hero_image.url, class: 'blog-tab-image', alt: article.slug %>
    </div>
    <div
      class="col-lg-8 col-md-7 col-12 position-relative blog-tab-content-wrapper"
    >
      <div class="blog-tab-content ">
        <h3 class="process-item-title mt-0"><%= article.title %></h3>
        <p class="home-text">
          <%= article.sub_title %>
        </p>
        <div class="blog-tab-footer position-absolute">
          <span class="text-uppercase">by: <%= article.authors.map {|a| a.name}.join(', ') %></span>
          <span class="text-uppercase news"><%= article.tags.map {|t| t.name}.join(', ') %></span>
          <span class="text-uppercase"><%= article.published_at.strftime('%d/%m/%Y') %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>